'use client';
import {useState} from 'react';
export function LeagueInvite({code,name}:{code:string;name:string}){
 const [message,setMessage]=useState('');const [qr,setQr]=useState('');const [generating,setGenerating]=useState(false);
 const url=`https://fcarena.in/leagues?code=${encodeURIComponent(code)}`;
 async function copy(){try{await navigator.clipboard.writeText(code);setMessage('League code copied');}catch{setMessage('Copy the league code shown above.');}}
 async function share(){try{const text=`Join ${name} on FC ARENA. League code: ${code}`;if(navigator.share)await navigator.share({title:name,text,url});else{await navigator.clipboard.writeText(`${text}\n${url}`);setMessage('Invite link copied');}}catch(error){if(!(error instanceof DOMException&&error.name==='AbortError'))setMessage('Use Copy code to invite a player.');}}
 async function showQR(){if(qr){setQr('');return;}setGenerating(true);try{const {toDataURL}=await import('qrcode');setQr(await toDataURL(url,{width:280,margin:4,errorCorrectionLevel:'M',color:{dark:'#102D4C',light:'#FFFFFF'}}));}catch{setMessage('Unable to create QR code. Please use Share invite.');}finally{setGenerating(false);}}
 return <section className="theme-panel rounded-xl p-4"><div className="flex flex-wrap items-center gap-3"><span className="w-full text-sm sm:w-auto sm:flex-1">Invite code <strong className="font-mono">{code}</strong></span><button onClick={()=>void copy()} className="theme-secondary-button rounded-lg px-4 text-sm">Copy code</button><button onClick={()=>void share()} className="theme-primary-button rounded-lg px-4 text-sm">Share invite</button><button disabled={generating} aria-expanded={!!qr} onClick={()=>void showQR()} className="theme-secondary-button rounded-lg px-4 text-sm">{generating?'Creating…':qr?'Hide QR':'Show QR'}</button></div>{qr&&<div className="mt-4 grid justify-items-center gap-2"><img src={qr} width={280} height={280} alt={`Scan to join ${name}`} className="max-w-full rounded-xl"/><p className="text-sm">Scan to open the league invite. Sign in to request membership.</p><a href={qr} download="fc-arena-league-invite.png" className="theme-secondary-button rounded-lg px-4 py-3 text-sm">Download QR</a></div>}<p role="status" className="text-sm">{message}</p></section>;
}
