ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MATCH_READY';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RESULT_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DISPUTE_OPENED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DISPUTE_RESOLVED';

ALTER TABLE "matches"
  ADD COLUMN "homeReadyAt" TIMESTAMP(3),
  ADD COLUMN "awayReadyAt" TIMESTAMP(3);
