'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { authenticatedRequest } from '@/lib/auth-client';
type Entry = { tournament:{id:string};registration:{id:string;status:string;entryName:string|null};statistics:{matches:number;wins:number;draws:number;losses:number} };
type Standing = {registrationId:string;position:number;points:number;played:number};
export function PlayerProgress({tournamentId}:{tournamentId:string}) {
 const [entry,setEntry]=useState<Entry|null>(null);const [standing,setStanding]=useState<Standing|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');void(async()=>{try{const career=await authenticatedRequest<{data:{tournamentHistory:Entry[]}}>('/players/me/career');const current=career.data.tournamentHistory.find(item=>item.tournament.id===tournamentId)??null;if(!active)return;setEntry(current);setStanding(null);if(current){const table=await authenticatedRequest<{data:{standings:Standing[]}}>(`/tournaments/${tournamentId}/standings`).catch(()=>null);if(active)setStanding(table?.data.standings.find(row=>row.registrationId===current.registration.id)??null);}}catch{if(active)setError('Your tournament progress could not be loaded.');}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[tournamentId,retry]);
 return <section className="theme-panel rounded-2xl p-5"><h2 className="font-semibold">Your tournament</h2>{loading?<p className="mt-2 animate-pulse text-sm">Loading your progress…</p>:error?<p role="alert" className="mt-2 text-sm">{error} <button onClick={()=>setRetry(n=>n+1)} className="theme-secondary-button rounded-lg px-3">Retry</button></p>:entry?<><p className="mt-2 text-sm">{entry.registration.entryName || 'Your entry'} · {entry.registration.status.replaceAll('_',' ')}</p><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><div><strong className="block text-xl">{entry.statistics.matches}</strong>Played</div><div><strong className="block text-xl">{entry.statistics.wins}</strong>Wins</div><div><strong className="block text-xl">{standing?.points ?? '—'}</strong>Points</div></div><p className="mt-3 text-sm">{standing ? `Overall table position #${standing.position}. Group qualification is shown in standings.` : 'Your position appears once standings are available.'}</p></>:<p className="mt-2 text-sm">You have no registered entry in this tournament yet. Open registration to check availability and apply.</p>}<div className="mt-4 flex flex-wrap gap-3"><Link className="theme-secondary-button rounded-lg px-4 py-2 text-sm" href={`/tournaments/${tournamentId}/registration`}>Registration</Link><Link className="theme-secondary-button rounded-lg px-4 py-2 text-sm" href={`/tournaments/${tournamentId}/standings`}>Standings & qualification</Link></div></section>;
}
